name: dice_roller
description: A casual, interactive, single user, dice rolling game.
publish_to: 'none' # Prevent accidental publishing to pub.dev.
version: 0.0.1+1

environment:
  sdk: ^3.0.1

dependencies:
  audioplayers: ^4.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.3
  flutter:
    sdk: flutter
  games_services: ^3.0.0
  go_router: ^8.0.1
  google_mobile_ads: ^3.0.0
  in_app_purchase: ^3.0.1
  logging: ^1.1.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.1.1
  test: ^1.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/dices/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf
